### ISSUE TITLE
[Epic] Next Build template QA

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#574]
## Description
This ticket is to ensure that Content Build migrated templates behave and look as expected in Next Build. This ticket is a way for us to track approval of the previously migrated templates. All migrated layouts should be approved before rolling out into production. QA will be provided by the sitewide team.

## QA Issue tracker
https://docs.google.com/spreadsheets/d/1Bt_vR8jOST2kzOiSoAvNgzcdyIsI1byhjwCsmyhhjyQ/edit?gid=675750633#gid=675750633

## Links to the layouts
Vets Center
https://dev.va.gov/abilene-vet-center
Press Release Listings
https://dev.va.gov/southern-nevada-health-care/news-releases
Press Release
https://dev.va.gov/southern-nevada-health-care/news-releases/vasnhs-to-host-laughlin-pact-act-veterans-town-hall-june-27/
Story Listings
https://dev.va.gov/eastern-oklahoma-health-care/stories/
News Story
https://dev.va.gov/eastern-oklahoma-health-care/stories/access-va-health-care-during-federal-holidays-and-247-365-with-va-health-connect/
Event Listings
https://dev.va.gov/outreach-and-events/events/
Event
https://dev.va.gov/outreach-and-events/events/69619/

## Acceptance Criteria
- [ ] News Story QA passed
- [ ] Vets Center QA passed
- [ ] Press Release Listings QA passed
- [ ] Press Release QA passed
- [ ] Story Listings QA passed
- [x] Event Listings QA passed
- [x] Events QA passed

## Supporting detail
Finalized templates will need their feature flags turned on in the CMS in order for them to be released.

**Comment by laflannery** [comment]
Closing, as this is is going to be replaced by QA of individual templates
